### PR TITLE
Fix typo in detectNocashPrintSupport and add support for melonDS

### LINKED ISSUE #72: detectNocashPrintSuppport only works with no$gba itself
melonDS also supports the nocash print registers, but it isn't being used because:
- `detectNocashPrintSuppport()` is checking for `0x67246F6E` (`no$g`)
- melonDS returns `0x6F6C656D` (`melo`) instead

Also this function has a typo in the name.

### PR DESCRIPTION
**Pull request by synthic**
Closes #72.

### CODE REVIEW

File: arm7/source/core/Environment.cpp [hunk 1]
```diff
@@ -15,10 +15,13 @@ static bool detectIsNitroEmulator()
     return true;
 }
 
-static bool detectNocashPrintSuppport()
+static bool detectNocashPrintSupport()
 {
     u32 nocashIdentifier = *(vu32*)0x04FFFA00;
-    return nocashIdentifier == 0x67246F6E; //no$g
+    // No$gba (no$g) or melonDS (melo)
+    if (nocashIdentifier == 0x67246F6E || nocashIdentifier == 0x6F6C656D)
```
Comment (Gericom) [inline arm7/source/core/Environment.cpp]: You can still write this as a return

Comment (Gericom) [inline arm7/source/core/Environment.cpp]: Let's create some defines for the magic numbers. Put them below the includes at the top of the file.

Comment (synthic) [reply arm7/source/core/Environment.cpp]: Thank you, I wasn't sure if that would actually work.

Comment (synthic) [reply arm7/source/core/Environment.cpp]: Will do. Hopefully that looks better now.

File: arm7/source/core/Environment.cpp [hunk 2]
```diff
@@ -15,10 +18,10 @@ static bool detectIsNitroEmulator()
     return true;
 }
 
-static bool detectNocashPrintSuppport()
+static bool detectNocashPrintSupport()
 {
     u32 nocashIdentifier = *(vu32*)0x04FFFA00;
-    return nocashIdentifier == 0x67246F6E; //no$g
+    return (nocashIdentifier == NOCASH_ID || nocashIdentifier == NOCASH_ID_MELONDS);
```
Comment (Gericom) [inline arm7/source/core/Environment.cpp]:
```suggestion
    return nocashIdentifier == NOCASH_ID || nocashIdentifier == NOCASH_ID_MELONDS;
```
