### PR TITLE
Add overlay patch to fix race condition in Kirby Super Star Ultra

### LINKED ISSUE #39: Kirby Super Star Ultra softlocks after unlocking sub games
Using an Unlabeled ace3sd clone on pico loader 1.10.0 and pico launcher 1.0. 
Similar to every other flashcart i've tested, the game will softlock and ignore all input after unlocking something on the corkboard main menu requiring a reset to continue to play the game. There's an action replay code to bypass this as a work around but naturally using something like that would invalidate something like speedruns.

### PR DESCRIPTION
**Pull request by taxicat1**
An animation delay of 16 frames happens at the same time as a save write, and then when the delay finishes, it waits for the save to complete. But if the save is already complete by this time, it will get stuck.

The problematic function is in overlay 6 so it needs an overlay patch. The patch reorders the check of the status of the save write so it will only call the function after the 16 frame delay is complete, instead of at every frame during the delay.

Function decompilation: https://decomp.me/scratch/yixvB

Fixes #39

### CODE REVIEW

**Comment by Gericom** [comment]
Maybe it would be good to add more background information about the patch in the code? Otherwise it'll end up being another magic patch.

File: arm9/source/patches/arm9/OverlayPatches/KirbySuperStarUltra/KirbySuperStarUltraPatch.cpp [hunk 1]
```diff
@@ -0,0 +1,41 @@
+#include "common.h"
+#include "gameCode.h"
+#include "../../../PatchContext.h"
```
Comment (Gericom) [inline arm9/source/patches/arm9/OverlayPatches/KirbySuperStarUltra/KirbySuperStarUltraPatch.cpp]: Maybe clearer to write patches/PatchContext.h here?

**Comment by Dartz150** [comment]
> Maybe it would be good to add more background information about the patch in the code? Otherwise it'll end up being another magic patch.

Agree, a brief explanation of the issue and what the patch does to solve it would be good.

File: arm9/source/patches/arm9/OverlayPatches/KirbySuperStarUltra/KirbySuperStarUltraPatch.h [hunk 2]
```diff
@@ -0,0 +1,11 @@
+#pragma once
+#include "../OverlayPatch.h"
+
+/// @brief Arm9 overlay patch for Kirby Super Star Ultra.
+class KirbySuperStarUltraPatch : public OverlayPatch
+{
+public:
+    KirbySuperStarUltraPatch() { }
```
Comment (Gericom) [inline arm9/source/patches/arm9/OverlayPatches/KirbySuperStarUltra/KirbySuperStarUltraPatch.h]: Is this constructor necessary if it doesn't do anything?
