### PR TITLE
DSProtect patches

### LINKED ISSUE #11: Support DS Protect v1.00/1.02
(This is one DS Protect version which is either 1.00 or 1.02, cannot figure out which)

It is identical to 1.05, except with these offsets:

stub_protectb1 = 0x0
stub_notprotectb1 = 0xDC
(stub_protectb2 does not exist)
(stub_notprotectb2 does not exist)
stub_protectb3 = 0x1B8
stub_notprotectb3 = 0x284

And the callback addresses are xored with 0x190 instead of 0x320, which means `dsprotectpatchv1_moveCallback = 0xE230EE19` for `eors lr, r0, #0x190`

These games have this version:
```
ANMK;0;1.02;110011;-2,0x105D80;-1;0x0
YFTK;0;1.02;110011;-2;0x69D40;-1,0x0
YFYK;0;1.02;110011;-2;0x69D40;-1,0x0
YV5E;0;1.02;000001;-2;0x7E74;-1;0x0
YV5J;0;1.02;000001;-2;0x7E74;-1;0x0
YV5P;0;1.02;000001;-2;0x7E74;-1;0x0
YVKK;0;1.02;010001;-2;0xF7064;-1;0x0
```
(I wrote 1.02 here just to pick one)

All of these are Korean games with the exception of Dragon Quest V

### PR DESCRIPTION
**Pull request by taxicat1**
- Simplify patch system to use function queue manipulation. This works by either overwriting a dangerous function pointer in DS Protect's processing queue to be null, or by copying another pointer in the queue to a harmless function like an integrity test. Can use the same patch for 1.X, 2.X, and 2.Xs. Patch assembles to size 0x4C
- Test the function deadstrip mask individually to build offsets for deadstrippable versions. This can now support any mask without having to add offsets for each one
- Add version 1.00/2 ("V1_00_2") support for aplist and tools. It was added to the end of the enum so as to not break when using an older aplist.bin.  Add known list of games that use this version into aplist.csv. No game uses this version in an overlay, though, so this has no effect yet. Resolves #11 

New patch system has worked for all test ROMs I compiled for it, but could probably use more rigorous testing on actual games just be 100% certain.

### CODE REVIEW

File: tools/PicoLoaderConverter/PicoLoaderConverter/ApList/ApListFactory.cs [hunk 1]
```diff
@@ -172,6 +172,7 @@ private DSProtectVersion ParseDSProtectVersion(string dsProtectVersion)
             "2.01s" => DSProtectVersion.V2_01s,
             "2.03s" => DSProtectVersion.V2_03s,
             "2.05s" => DSProtectVersion.V2_05s,
+            "1.00_2" => DSProtectVersion.V1_00_2,
```
Comment (Gericom) [inline tools/PicoLoaderConverter/PicoLoaderConverter/ApList/ApListFactory.cs]: Although the enum is not sorted, you can keep this switch sorted.

Please add to `FormatDSProtectVersion` as well
